---
driver:
  name: vagrant
  customize: 
     memory: 768
  log_file: "/var/log/chef/chef-client.log"

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[duo-unix::default]